export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DIRECTORY_ROUTE = '/'
export const MAGAZINE_ROUTE = '/getMagazineInfo'